B4J=true
Group=Classes
ModulesStructureVersion=1
Type=StaticCode
Version=10.3
@EndOfDesignText@
' Reference: https://www.rapidtables.com/code/text/ascii-table.html
Sub Process_Globals
	Public NUL As String = Chr(0)
	Public SOH As String = Chr(1)
	Public STX As String = Chr(2)
	Public ETX As String = Chr(3)
'	Public EOT As String = Chr(4)
'	Public ENQ As String = Chr(5)
'	Public ACK As String = Chr(6)
'	Public BEL As String = Chr(7)
'	Public BS As String = Chr(8)
'	Public HT As String = Chr(9)
'	Public LF As String = Chr(10)
'	Public VT As String = Chr(11)
'	Public FF As String = Chr(12)
'	Public CR As String = Chr(13)
'	Public SO As String = Chr(14)
'	Public SI As String = Chr(15)
'	Public DLE As String = Chr(16)
'	Public DC1 As String = Chr(17)
'	Public DC2 As String = Chr(18)
'	Public DC3 As String = Chr(19)
'	Public DC4 As String = Chr(20)
'	Public NAK As String = Chr(21)
'	Public SYN As String = Chr(22)
'	Public ETB As String = Chr(23)
'	Public CAN As String = Chr(24)
'	Public EM As String = Chr(25)
'	Public SUB As String = Chr(26)
	Public ESC As String = Chr(27)
	Public FS As String = Chr(28)
	Public GS As String = Chr(29)
'	Public RS As String = Chr(30)
'	Public US As String = Chr(31)
	Public Space As String = Chr(32) ' " "
	Public Exclamation As String = Chr(33) ' !
'	Public QUOTE As String = Chr(34) ' "
	Public Hash As String = Chr(35) ' #
	Public Dollar As String = Chr(36) ' $
	Public Percent As String = Chr(37) ' %
	Public Ampersand As String = Chr(38) ' &
	Public SingleQuote As String = Chr(39) ' '
	Public OpenBracket As String = Chr(40) ' (
	Public CloseBracket As String = Chr(41) ' )
	Public Astericks As String = Chr(42) ' *
	'Public Plus As String = Chr(43) ' +
	'Public Comma As String = Chr(44) ' ,
	'Public Minus As String = Chr(45) ' -
	'Public Period As String = Chr(46) ' .
	'Public Slash As String = Chr(47) ' /
	Public Num0 As String = Chr(48) ' 0
	Public Num1 As String = Chr(49) ' 1
	Public Num2 As String = Chr(50) ' 2
	Public Num3 As String = Chr(51) ' 3
	Public Num4 As String = Chr(52) ' 4
	Public Num5 As String = Chr(53) ' 5
	
	Public Question As String = Chr(63) ' ?
	Public At As String = Chr(64) ' @
	Public UC_A As String = Chr(65) ' A
	Public B As String = Chr(66) ' B
	Public C As String = Chr(67) ' C
	Public D As String = Chr(68) ' D
	Public E As String = Chr(69) ' E
	Public F As String = Chr(70) ' F
	Public G As String = Chr(71) ' G
	Public H As String = Chr(72) ' H
	Public I As String = Chr(73) ' I
	Public J As String = Chr(74) ' J
	Public K As String = Chr(75) ' K
	Public L As String = Chr(76) ' L
	Public M As String = Chr(77) ' M
	Public W As String = Chr(87) ' W
	Public X As String = Chr(88) ' X
	Public Y As String = Chr(89) ' Y
	Public Z As String = Chr(90) ' Z
	
	Public BackSlash As String = Chr(92) ' \
	Public LC_a As String = Chr(97) ' a
	Public LC_b As String = Chr(98) ' b
	Public LC_c As String = Chr(99) ' c
	Public LC_d As String = Chr(100) ' d
	Public LC_t As String = Chr(116) ' t
End Sub
